### PR TITLE
Add MaxPool2D backward reference

### PR DESCRIPTION
**Pull request by apertovs**

### CODE REVIEW

**Comment by RodionovF** [comment]
lgtm

**Comment by TolyaTalamanov** [comment]
Don't dive deep, @l-bat have a look, I'm OK if it works

**Comment by TolyaTalamanov** [comment]
BTW restart CI

```
git commit --amend --allow-empty
git push -f <remote> HEAD
```

**Comment by TolyaTalamanov** [comment]
Thanks! 👍

**Comment by TolyaTalamanov** [comment]
@apertovs  Reverted due build fail

**Pull request merged**
