### PR TITLE
Setup project skeleton

### PR DESCRIPTION
**Pull request by TolyaTalamanov**

### CODE REVIEW

**Comment by TolyaTalamanov** [comment]
@apertovs Have a look, please

**Comment by apertovs** [comment]
Looks good to me

**Comment by TolyaTalamanov** [comment]
FYI @l-bat

**Review by l-bat — APPROVED** [review]
:+1:

**Comment by TolyaTalamanov** [comment]
@KSTconsult

**Comment by TolyaTalamanov** [comment]
@RodionovF

**Comment by TolyaTalamanov** [comment]
@apertovs @KSTconsult  @apertovs @RodionovF 
Guys have a look

CI is passed: https://travis-ci.com/github/NeuralDeepWorks/deepworks/builds/218018247

**Comment by apertovs** [comment]
+1

**Comment by RodionovF** [comment]
:+1:

**Pull request merged**
